apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: hiepnnt/udagram-frontend:v10
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80